'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),controls=['detail','contrast','threshold','edge','grain'];
const palettes={studio:{paper:'#e4e4df',ink:'#262624',accent:'#a3a39c'},lilac:{paper:'#939a92',ink:'#f5f0e8',accent:'#b48bdf'},blue:{paper:'#e5edf1',ink:'#1838a5',accent:'#718aed'},red:{paper:'#f6d9db',ink:'#591c29',accent:'#db4c58'}};
const defaults={mode:'contour',palette:'studio',detail:65,contrast:45,threshold:50,edge:45,grain:12,invert:false};
const state={...defaults,colors:{...palettes.studio}};
const descriptions={contour:'Soft contours. Fine dots. A little imperfection.',halftone:'A rhythm of dots that follows every shade.',stipple:'Scattered ink. Fine grain. Organic detail.',lines:'Continuous lines shaped by light and shadow.'};
let source=null,baseW=1200,baseH=1200,original=false,frame=0,loadId=0,name='Butterfly',exporting=false;
function notice(message){$('notice').textContent=message}
function hash(x,y,seed=0){let n=Math.imul(x+seed+1,374761393)^Math.imul(y+1,668265263);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967295}
function render(target,width,height,settings=state,image=source,bw=baseW,bh=baseH){target.width=width;target.height=height;const c=target.getContext('2d');if(!image)return;const p=settings.colors;c.fillStyle=p.paper;c.fillRect(0,0,width,height);const long=Math.max(bw,bh),cell=(5+(95-settings.detail)*.22)*long/1200,cols=Math.max(1,Math.ceil(bw/cell)),rows=Math.max(1,Math.ceil(bh/cell)),sx=width/cols,sy=height/rows,size=Math.min(sx,sy);
const small=document.createElement('canvas');small.width=cols;small.height=rows;const sc=small.getContext('2d',{willReadFrequently:true});sc.fillStyle='#ffffff';sc.fillRect(0,0,cols,rows);sc.drawImage(image,0,0,cols,rows);const data=sc.getImageData(0,0,cols,rows).data,tones=new Float32Array(cols*rows),factor=.6+settings.contrast/55,bias=(settings.threshold-50)/130;
for(let i=0;i<tones.length;i++){const k=i*4,l=(data[k]*.2126+data[k+1]*.7152+data[k+2]*.0722)/255;let d=(1-l-.5)*factor+.5+bias;if(settings.invert)d=1-d;tones[i]=Math.max(0,Math.min(1,d))}
const at=(x,y)=>tones[Math.max(0,Math.min(rows-1,y))*cols+Math.max(0,Math.min(cols-1,x))],strength=settings.edge/100;
function circle(x,y,r,color){if(r<=0)return;c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
c.lineCap='round';c.lineJoin='round';
for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const d=at(x,y),px=(x+.5)*sx,py=(y+.5)*sy,gradient=Math.hypot(at(x+1,y)-at(x-1,y),at(x,y+1)-at(x,y-1))/2;
if(settings.mode==='halftone'){if(d<.012)continue;const ox=(y%2)*sx*.35;circle(px+ox,py,size*.49*Math.sqrt(d),p.ink);if(strength&&gradient>.28)circle(px+ox,py,size*.13*strength,p.accent)}
else if(settings.mode==='stipple'){const density=d*9,count=Math.floor(density)+(hash(x,y,42)<density%1?1:0);for(let j=0;j<count;j++){const xx=(x+hash(x,y,13+j*11))*sx,yy=(y+hash(y,x,21+j*17))*sy,r=size*(.055+.048*hash(x,y,j+33));circle(xx,yy,r,gradient>.3&&hash(x,y,j+41)<strength*.4?p.accent:p.ink)}}
else if(settings.mode==='lines'){if(d<.035)continue;const next=at(x+1,y),wave=Math.sin(x*.24+y*.17)*sy*.23;c.strokeStyle=gradient>.3&&hash(x,y,8)<strength*.55?p.accent:p.ink;c.lineWidth=Math.max(size*.035,sy*(.04+.52*(d+next)/2));c.beginPath();c.moveTo(x*sx,(y+.5)*sy+wave);c.lineTo((x+1)*sx,(y+.5)*sy+Math.sin((x+1)*.24+y*.17)*sy*.23);c.stroke()}
else{if(d<.035)continue;const levels=[.22,.5,.77],boundary=levels.some(t=>(d>=t)!==(at(x-1,y)>=t)||(d>=t)!==(at(x+1,y)>=t)||(d>=t)!==(at(x,y-1)>=t)||(d>=t)!==(at(x,y+1)>=t));if(d>.15){const n=d>.72?3:2;for(let j=0;j<n;j++)for(let k=0;k<n;k++){const r=size*(.065+.07*d);circle((x+(j+.5)/n)*sx,(y+(k+.5)/n)*sy,r,p.ink)}}if(boundary&&d>.18){circle(px,py,size*(.30+.28*strength),p.ink);if(gradient>.22&&hash(x,y,7)<strength*.8)circle(px,py,size*.28,p.accent)}}}
if(settings.grain>0){const gw=Math.max(1,Math.round(bw*Math.min(1,600/long))),gh=Math.max(1,Math.round(bh*Math.min(1,600/long))),paper=document.createElement('canvas');paper.width=gw;paper.height=gh;const pc=paper.getContext('2d'),noise=pc.createImageData(gw,gh);for(let y=0;y<gh;y++)for(let x=0;x<gw;x++){const i=(y*gw+x)*4,v=hash(x,y,101)>.5?255:0;noise.data[i]=v;noise.data[i+1]=v;noise.data[i+2]=v;noise.data[i+3]=hash(x,y,103)*settings.grain*.65}pc.putImageData(noise,0,0);c.imageSmoothingEnabled=false;c.drawImage(paper,0,0,width,height)}
}
function draw(){if(!source)return;const ratio=Math.min(1,1100/Math.max(baseW,baseH)),w=Math.max(1,Math.round(baseW*ratio)),h=Math.max(1,Math.round(baseH*ratio));if(original){canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(source,0,0,w,h)}else render(canvas,w,h);$('renderStatus').textContent=original?'ORIGINAL':'LIVE / '+state.mode.toUpperCase();$('dimensions').textContent=`${baseW} × ${baseH} PX`}
function schedule(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}
function syncColors(){for(const key of ['paper','ink','accent']){$(key+'Color').value=state.colors[key];$(key+'Hex').value=state.colors[key].toUpperCase();$(key+'Hex').removeAttribute('aria-invalid')}document.querySelectorAll('[data-palette]').forEach(b=>{const active=b.dataset.palette===state.palette;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
function sync(){for(const id of controls){$(id).value=state[id];$(id+'Val').textContent=state[id]}document.querySelectorAll('[data-mode]').forEach(b=>{const a=b.dataset.mode===state.mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});$('effectDescription').textContent=descriptions[state.mode];$('invert').setAttribute('aria-pressed',String(state.invert));syncColors();schedule()}
function reset(){Object.assign(state,defaults);state.colors={...palettes.studio};original=false;$('compare').setAttribute('aria-pressed','false');sync();notice('IMAGES STAY ON YOUR DEVICE.')}
for(const id of controls)$(id).addEventListener('input',()=>{state[id]=Number($(id).value);$(id+'Val').textContent=state[id];schedule()});
function selectTab(tab,focus=false){for(const name of ['texture','tune','color']){const a=tab===name;$(name+'Tab').setAttribute('aria-selected',String(a));$(name+'Tab').tabIndex=a?0:-1;$(name+'Panel').hidden=!a}if(focus)$(tab+'Tab').focus()}
document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)selectTab(b.dataset.tab)});document.querySelector('.tabs').addEventListener('keydown',e=>{const names=['texture','tune','color'],i=names.indexOf(e.target.dataset.tab);if(i<0)return;let next;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();selectTab(names[next],true)});
$('presets').onclick=e=>{const b=e.target.closest('[data-mode]');if(b){state.mode=b.dataset.mode;sync()}};$('swatches').onclick=e=>{const b=e.target.closest('[data-palette]');if(b){state.palette=b.dataset.palette;state.colors={...palettes[state.palette]};syncColors();schedule()}};
function normalizeHex(v){v=v.trim();if(/^#?[0-9a-f]{3}$/i.test(v)){const a=v.replace('#','');return '#'+[...a].map(c=>c+c).join('').toLowerCase()}if(/^#?[0-9a-f]{6}$/i.test(v))return '#'+v.replace('#','').toLowerCase();return null}
for(const key of ['paper','ink','accent']){$(key+'Color').addEventListener('input',()=>{state.colors[key]=$(key+'Color').value;state.palette='custom';syncColors();schedule()});$(key+'Hex').addEventListener('input',()=>{const color=normalizeHex($(key+'Hex').value);if(color){state.colors[key]=color;state.palette='custom';$(key+'Color').value=color;$(key+'Hex').removeAttribute('aria-invalid');document.querySelectorAll('[data-palette]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});schedule()}});$(key+'Hex').addEventListener('blur',()=>{const color=normalizeHex($(key+'Hex').value);if(color){$(key+'Hex').value=color.toUpperCase()}else{$(key+'Hex').value=state.colors[key].toUpperCase();notice('USE A HEX COLOR, LIKE #E5CA45.')}})}
$('reset').onclick=reset;$('resetTune').onclick=()=>{for(const k of controls)state[k]=defaults[k];sync()};$('invert').onclick=()=>{state.invert=!state.invert;sync()};$('upload').onclick=()=>$('file').click();$('compare').onclick=()=>{if(!source)return;original=!original;$('compare').setAttribute('aria-pressed',String(original));draw()};
async function loadImage(url,label){const id=++loadId,img=new Image();img.src=url;await img.decode();if(id!==loadId)return;const max=Math.min(1,2400/Math.max(img.naturalWidth,img.naturalHeight),Math.sqrt(6000000/(img.naturalWidth*img.naturalHeight))),w=Math.max(1,Math.round(img.naturalWidth*max)),h=Math.max(1,Math.round(img.naturalHeight*max)),normalized=document.createElement('canvas');normalized.width=w;normalized.height=h;normalized.getContext('2d').drawImage(img,0,0,w,h);normalized.getContext('2d').getImageData(0,0,1,1);source=normalized;baseW=w;baseH=h;name=label.replace(/\.[^.]+$/,'');$('filename').textContent=label.toUpperCase();original=false;$('compare').setAttribute('aria-pressed','false');draw();notice(max<1?'LARGE IMAGE RESIZED FOR RELIABLE EXPORTS.':'IMAGES STAY ON YOUR DEVICE.')}
async function openFile(file){if(!file)return;if(!file.type.startsWith('image/')&&!/\.(png|jpe?g|webp|gif|avif|bmp|svg)$/i.test(file.name)){notice('CHOOSE AN IMAGE FILE.');return}if(file.size>30*1024*1024){notice('CHOOSE AN IMAGE UNDER 30 MB.');return}const url=URL.createObjectURL(file);$('renderStatus').textContent='OPENING…';try{await loadImage(url,file.name)}catch{notice('COULD NOT OPEN IMAGE. TRY PNG, JPG OR WEBP.');draw();if(!source)$('renderStatus').textContent='OPEN AN IMAGE'}finally{URL.revokeObjectURL(url);$('file').value=''}}
$('file').onchange=e=>openFile(e.target.files[0]);let dragDepth=0;const drop=$('drop');drop.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;drop.classList.add('drag')});drop.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'});drop.addEventListener('dragleave',e=>{e.preventDefault();if(--dragDepth<=0)drop.classList.remove('drag')});drop.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;drop.classList.remove('drag');openFile(e.dataTransfer.files[0])});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
async function exportPNG(scale){if(!source||exporting)return;exporting=true;$('export1').disabled=$('export2').disabled=true;notice(`PREPARING ${scale}× PNG…`);const snapshot={...state,colors:{...state.colors}},w=baseW*scale,h=baseH*scale,exportName=name,image=source,bw=baseW,bh=baseH;let out;try{await new Promise(r=>setTimeout(r,30));out=document.createElement('canvas');render(out,w,h,snapshot,image,bw,bh);const blob=await new Promise((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('PNG encoding failed')),'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${exportName.replace(/[^a-z0-9_-]/gi,'-')}-fuzool-${scale}x.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);notice(`SAVED ${scale}× / ${w} × ${h} PX`)}catch{notice('EXPORT FAILED. TRY A SMALLER IMAGE.')}finally{if(out)out.width=out.height=1;exporting=false;$('export1').disabled=$('export2').disabled=false}}
$('export1').onclick=()=>exportPNG(1);$('export2').onclick=()=>exportPNG(2);
function tick(){$('clock').textContent=new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}tick();setInterval(tick,1000);
loadImage('sample.png','Butterfly.png').catch(()=>{$('filename').textContent='NO IMAGE';$('renderStatus').textContent='OPEN AN IMAGE';notice('DROP A PHOTO TO BEGIN.')});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_texture',description:'Configure the current texture and custom colors in the image editor.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:Object.keys(descriptions)},palette:{type:'string',enum:Object.keys(palettes)},detail:{type:'number',minimum:15,maximum:95},contrast:{type:'number',minimum:0,maximum:100},threshold:{type:'number',minimum:0,maximum:100},edge:{type:'number',minimum:0,maximum:100},grain:{type:'number',minimum:0,maximum:70},invert:{type:'boolean'},colors:{type:'object',properties:{paper:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},ink:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},accent:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}},additionalProperties:false}},additionalProperties:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected texture settings');for(const [k,v] of Object.entries(input)){if(k==='mode'&&!Object.hasOwn(descriptions,v)||k==='palette'&&!Object.hasOwn(palettes,v)||k==='invert'&&typeof v!=='boolean'||controls.includes(k)&&(typeof v!=='number'||!Number.isFinite(v)||v<(k==='detail'?15:0)||v>(k==='grain'?70:k==='detail'?95:100))||!Object.hasOwn(state,k))throw new Error('Invalid setting');if(k==='colors'){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Invalid colors');for(const [key,color] of Object.entries(v))if(!['paper','ink','accent'].includes(key)||typeof color!=='string'||!/^#[0-9a-f]{6}$/i.test(color))throw new Error('Invalid color')}}const nextColors=input.palette?{...palettes[input.palette]}:{...state.colors};if(input.colors)Object.assign(nextColors,input.colors);Object.assign(state,input,{colors:nextColors});if(input.colors)state.palette='custom';sync();draw();return {...state,colors:{...state.colors}}},annotations:{readOnlyHint:false,untrustedContentHint:false}})).catch(()=>{})}catch{}}

